esphome:
  name: displayring
  friendly_name: DisplayRing

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Displayring Fallback Hotspot"
    password: !secret captive_portal_password

captive_portal:

# To have a "next url" for improv serial
web_server:

# Allow provisioning Wi-Fi via serial
improv_serial:


# Display ring 
output:
  - platform: esp8266_pwm
    pin: GPIO4
    frequency: 1000 Hz
    id: pwm_output
    inverted: false

light:
  - platform: monochromatic
    name: "Display Ring"
    id: displayring
    output: pwm_output
    effects:
      - flicker:
          name: "Flicker"
          alpha: 95%
          intensity: 5%
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s

# Vibration sensor on D3 (GPIO0)
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
    name: "Tap Sensor"
    device_class: vibration
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      then:
        - light.toggle: 
            id: displayring